Um array de NumPy é uma estrutura de dados multidimensional que armazena elementos do mesmo tipo, facilitando operações matemáticas eficientes em Python.
É mais rápido que uma lista em Python porque armazena os dados de forma contígua na memória e utiliza operações vetorizadas, otimizando a execução de operações matemáticas e reduzindo a sobrecarga de looping em comparação com listas.

In [1]:
import numpy as np

In [2]:
a =np.array([1.0, 4.2,-3.1,10.0])

In [3]:
a

array([ 1. ,  4.2, -3.1, 10. ])

Uma operação vetorizada é aquela em que uma única operação é aplicada a todos os elementos de um array simultaneamente, em vez de iterar sobre cada elemento individualmente.

In [4]:
a+10

array([11. , 14.2,  6.9, 20. ])

In [8]:
b= np.array([[1,2,3], [1.1,2.2,3.3]]) # matrix, mesmo numero de itens

In [11]:
b+10

array([[11. , 12. , 13. ],
       [11.1, 12.2, 13.3]])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
# square matrix - a diaginal precisa ser 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# diaginal matrix
np.diag([10, 20, -80])

array([[ 10,   0,   0],
       [  0,  20,   0],
       [  0,   0, -80]])

In [16]:
# resize array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [17]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
a

array([1, 2, 3, 4, 5, 6])

In [19]:
np.reshape(a,(3,2)) #alternativa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
a

array([1, 2, 3, 4, 5, 6])

In [21]:
#ramdom
np.random.randint(low=1,high=6,size=10) #high exclude

array([3, 1, 4, 4, 1, 1, 5, 1, 2, 3])

In [22]:
np.random.rand(5)

array([0.94509949, 0.28621878, 0.97624338, 0.08243982, 0.87044729])

In [25]:
np.random.uniform(0,3,20).reshape((4,5))

array([[2.05921848, 2.86163487, 1.98746883, 0.25492519, 1.78586607],
       [2.51896153, 1.43032103, 0.00957332, 1.98577404, 1.73228825],
       [0.27644128, 0.38087578, 0.58592515, 2.49430977, 0.34261742],
       [1.12867456, 1.26561091, 1.30283181, 2.61674134, 0.86496132]])

In [28]:
np.random.standard_normal(24).reshape(6,4)
# Nesta distribuição, a média é 0 e o desvio padrão é 1

array([[ 0.36274975, -0.33812339, -0.24019278, -0.38845339],
       [-1.83902531, -0.70855679, -0.90436787,  0.80756755],
       [-1.36747765, -0.37219854,  1.81071535, -0.03143311],
       [ 0.12764132,  0.50712754,  1.07502103,  1.8990035 ],
       [-0.07782278, -0.073726  ,  0.03727425,  0.26865266],
       [ 0.39879058,  0.38657312,  0.25338786, -0.73418082]])

In [29]:
np.random.normal(100,10,10)

array([110.93768706, 106.40430504,  93.20843484, 100.99822903,
       112.15703421,  95.01992803,  96.89682066, 106.8858141 ,
        85.92518815,  98.30926128])

Essa função específica, np.random.normal(), é usada para gerar uma matriz de números aleatórios com distribuição normal (ou gaussiana). Aqui está o que cada argumento representa:

O primeiro argumento 100 é a média da distribuição normal.
O segundo argumento 10 é o desvio padrão da distribuição normal.
O terceiro argumento 10 especifica o tamanho da matriz que você deseja gerar, neste caso, uma matriz de 10 elementos.

In [30]:
np.random.lognormal(0.1,0.4,10)

array([1.33059892, 1.41123582, 0.6850126 , 0.48072753, 0.58365992,
       0.58262599, 0.6765682 , 2.13497677, 1.00141066, 1.25026205])

é usada para gerar uma matriz de números aleatórios com distribuição log-normal. Aqui está o que cada argumento representa:

O primeiro argumento 0.1 é a média da distribuição log-normal na escala natural do logaritmo.
O segundo argumento 0.4 é o desvio padrão da distribuição log-normal na escala natural do logaritmo.
O terceiro argumento 10 especifica o tamanho da matriz que você deseja gerar, neste caso, uma matriz de 10 elementos.