In [1]:
import pandas as pd
import numpy as np

In [9]:
s2 = pd.Series([3.3, 29.1, 20.2, 39.5, 12.8], index = ["UT","TX", "NY", "CA", "IL"], name = "Population")

In [10]:
pop_growth = [0.18, 0.16, 0.04, 0.06, 0]

In [7]:
pd.DataFrame(s2) #a primeira coluna é index e não coluna

Population
UT         3.3
TX        29.1
NY        20.2
CA        39.5
IL        12.8

In [11]:
pd.DataFrame({"pop":s2, "growth": pop_growth}) # dicionario de colunas

pop  growth
UT   3.3    0.18
TX  29.1    0.16
NY  20.2    0.04
CA  39.5    0.06
IL  12.8    0.00

In [18]:
data1= np.arange(1,16).reshape(5,3)
data1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [20]:
data = pd.DataFrame(data1) # nome das colunas automatico
data

0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [23]:
df1 =pd.DataFrame(data1, columns= ["a", "b", "c"]) #renomear colunas
df1


a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15

In [26]:
df2 =pd.DataFrame(data1, columns= ["a", "b", "c"], index = ["a","b","c","d","e"]) #tuplas ou listas
df2

a   b   c
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12
e  13  14  15

In [27]:
s2["UT"]#index com series

3.3

In [28]:
df2["b"] # em df no index é a coluna

a     2
b     5
c     8
d    11
e    14
Name: b, dtype: int64

In [30]:
states = pd.DataFrame({"pop":s2, "growth": pop_growth}) # dicionario de colunas
states

pop  growth
UT   3.3    0.18
TX  29.1    0.16
NY  20.2    0.04
CA  39.5    0.06
IL  12.8    0.00

In [31]:
states.to_numpy()# convert to numpy

array([[ 3.3 ,  0.18],
       [29.1 ,  0.16],
       [20.2 ,  0.04],
       [39.5 ,  0.06],
       [12.8 ,  0.  ]])

In [32]:
states.values # nao aconselhavel

array([[ 3.3 ,  0.18],
       [29.1 ,  0.16],
       [20.2 ,  0.04],
       [39.5 ,  0.06],
       [12.8 ,  0.  ]])

In [35]:
states.growth.max() # nao é a melhor abordagem

0.18

In [36]:
states["growth"].max() # melhor abordagem

0.18

In [37]:
states["pop"].sum()

104.89999999999999

In [38]:
states["pop_2010"] =states["pop"]/(1+states["growth"]) # adicionar coluna
states

pop  growth   pop_2010
UT   3.3    0.18   2.796610
TX  29.1    0.16  25.086207
NY  20.2    0.04  19.423077
CA  39.5    0.06  37.264151
IL  12.8    0.00  12.800000

In [40]:
states = states.rename({"pop":"pop_2020"}, axis = 1)# rename retorna novo df

In [41]:
states

pop_2020  growth   pop_2010
UT       3.3    0.18   2.796610
TX      29.1    0.16  25.086207
NY      20.2    0.04  19.423077
CA      39.5    0.06  37.264151
IL      12.8    0.00  12.800000