Um array de NumPy é uma estrutura de dados multidimensional que armazena elementos do mesmo tipo, facilitando operações matemáticas eficientes em Python.
É mais rápido que uma lista em Python porque armazena os dados de forma contígua na memória e utiliza operações vetorizadas, otimizando a execução de operações matemáticas e reduzindo a sobrecarga de looping em comparação com listas.

In [1]:
import numpy as np

In [2]:
a =np.array([1.0, 4.2,-3.1,10.0])

In [3]:
a

array([ 1. ,  4.2, -3.1, 10. ])

In [4]:
a+10

array([11. , 14.2,  6.9, 20. ])

In [8]:
b= np.array([[1,2,3], [1.1,2.2,3.3]]) # matrix, mesmo numero de itens

In [6]:
b

array([[1. , 2. , 3. ],
       [1.1, 2.2, 3.3]])