Um array de NumPy é uma estrutura de dados multidimensional que armazena elementos do mesmo tipo, facilitando operações matemáticas eficientes em Python.
É mais rápido que uma lista em Python porque armazena os dados de forma contígua na memória e utiliza operações vetorizadas, otimizando a execução de operações matemáticas e reduzindo a sobrecarga de looping em comparação com listas.

In [2]:
import numpy as np

In [3]:
a =np.array([1.0, 4.2,-3.1,10.0])

In [4]:
a

array([ 1. ,  4.2, -3.1, 10. ])

Uma operação vetorizada é aquela em que uma única operação é aplicada a todos os elementos de um array simultaneamente, em vez de iterar sobre cada elemento individualmente.

In [5]:
a+10

array([11. , 14.2,  6.9, 20. ])

In [6]:
b= np.array([[1,2,3], [1.1,2.2,3.3]]) # matrix, mesmo numero de itens

In [7]:
b+10

array([[11. , 12. , 13. ],
       [11.1, 12.2, 13.3]])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
# square matrix - a diaginal precisa ser 1
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
# diaginal matrix
np.diag([10, 20, -80])

array([[ 10,   0,   0],
       [  0,  20,   0],
       [  0,   0, -80]])

In [13]:
# resize array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [14]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
a

array([1, 2, 3, 4, 5, 6])

In [16]:
np.reshape(a,(3,2)) #alternativa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
a

array([1, 2, 3, 4, 5, 6])

In [18]:
#ramdom
np.random.randint(low=1,high=6,size=10) #high exclude

array([3, 1, 4, 2, 4, 3, 1, 2, 5, 3])

In [19]:
np.random.rand(5)

array([0.71299912, 0.70373162, 0.98485806, 0.7063259 , 0.16302382])

In [20]:
np.random.uniform(0,3,20).reshape((4,5))

array([[1.08897639, 1.1313187 , 2.43330355, 0.14802439, 1.69126304],
       [0.92645619, 1.86644371, 2.40097268, 1.37812833, 1.87068527],
       [1.66920473, 2.51187447, 1.20208523, 2.41866797, 0.81182373],
       [2.61355554, 1.83658761, 2.31380477, 1.6493389 , 2.29473227]])

In [21]:
np.random.standard_normal(24).reshape(6,4)
# Nesta distribuição, a média é 0 e o desvio padrão é 1

array([[-0.23489404, -0.95928065,  1.56975494,  0.86048983],
       [ 0.76139925,  0.20945128,  0.24435108,  0.40341162],
       [ 1.19477363, -1.81898422, -0.36575118,  0.43952504],
       [-0.34588492, -2.03881662,  0.95472758,  0.68932794],
       [ 0.12913446, -1.61279186, -1.03135671, -2.43674156],
       [-0.74311118, -0.92441478, -1.03508474, -0.32716282]])

In [22]:
np.random.normal(100,10,10)

array([111.74265667, 113.00469597,  96.86421238,  94.65411626,
        93.8688077 , 114.2895568 , 108.30685573,  99.92908137,
        92.1247781 , 105.17929582])

Essa função específica, np.random.normal(), é usada para gerar uma matriz de números aleatórios com distribuição normal (ou gaussiana). Aqui está o que cada argumento representa:

O primeiro argumento 100 é a média da distribuição normal.
O segundo argumento 10 é o desvio padrão da distribuição normal.
O terceiro argumento 10 especifica o tamanho da matriz que você deseja gerar, neste caso, uma matriz de 10 elementos.

In [23]:
np.random.lognormal(0.1,0.4,10)

array([1.08827738, 1.15597479, 1.27690296, 3.55522322, 0.38185325,
       0.93044652, 1.00292836, 1.46269908, 0.34270367, 0.52089318])

é usada para gerar uma matriz de números aleatórios com distribuição log-normal. Aqui está o que cada argumento representa:

O primeiro argumento 0.1 é a média da distribuição log-normal na escala natural do logaritmo.
O segundo argumento 0.4 é o desvio padrão da distribuição log-normal na escala natural do logaritmo.
O terceiro argumento 10 especifica o tamanho da matriz que você deseja gerar, neste caso, uma matriz de 10 elementos.

In [24]:
cards = list(range(1,14))
cards

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [25]:
np.random.shuffle(cards) # inplace, tb faz com np array
cards

[6, 1, 2, 11, 9, 10, 3, 4, 5, 8, 12, 7, 13]

In [26]:
np.random.choice(cards,4)

array([ 3, 11, 11,  5])

Math with Arrays

In [27]:
a

array([1, 2, 3, 4, 5, 6])

In [28]:
a +100 #scalar

array([101, 102, 103, 104, 105, 106])

In [29]:
b = np.random.random(6)
b

array([0.34686109, 0.76401627, 0.59694951, 0.41642459, 0.17313569,
       0.33679853])

In [30]:
a+b

array([1.34686109, 2.76401627, 3.59694951, 4.41642459, 5.17313569,
       6.33679853])

In [31]:
A =np.arange(1,13).reshape(3,4)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
B =np.arange(101,113).reshape(3,4)
B

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112]])

In [33]:
A+B

array([[102, 104, 106, 108],
       [110, 112, 114, 116],
       [118, 120, 122, 124]])

Existe uma convenção comum na comunidade científica e de programação, incluindo o uso de NumPy, em que se utiliza letras maiúsculas para matrizes (ou arrays multidimensionais) e letras minúsculas para vetores (ou arrays unidimensionais)

In [34]:
X = np.array([[1,2],[10,4],[3,7]])
X

array([[ 1,  2],
       [10,  4],
       [ 3,  7]])

In [35]:
Y =np.arange(4,10).reshape(2,3)
Y

array([[4, 5, 6],
       [7, 8, 9]])

In [36]:
X.shape

(3, 2)

In [37]:
Y.shape

(2, 3)

In [38]:
np.matmul(X,Y)

array([[18, 21, 24],
       [68, 82, 96],
       [61, 71, 81]])

In [39]:
np.matmul(Y,X)

array([[ 72,  70],
       [114, 109]])

Index

In [40]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
A[0,0]

1

In [42]:
A[0]

array([1, 2, 3, 4])

In [43]:
A[0, :]

array([1, 2, 3, 4])

In [44]:
A[:,2] # buscar coluna

array([ 3,  7, 11])

In [45]:
A[1, 1:3]

array([6, 7])

In [46]:
A[1:,3]

array([ 8, 12])

In [47]:
A[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [49]:
A[1,0]=50
A

array([[ 1,  2,  3,  4],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
A[0] = 2
A

array([[ 2,  2,  2,  2],
       [50,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
A.sum()

121

In [52]:
A[1].sum()

71

In [53]:
A[:,2].max()

11

In [54]:
A.mean() #media

10.083333333333334